// Code generated by "stringer --type DroidOrderSybType"; DO NOT EDIT.

package wznet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DroidOrderSybTypeObj-0]
	_ = x[DroidOrderSybTypeLoc-1]
	_ = x[DroidOrderSybTypeSec-2]
}

const _DroidOrderSybType_name = "DroidOrderSybTypeObjDroidOrderSybTypeLocDroidOrderSybTypeSec"

var _DroidOrderSybType_index = [...]uint8{0, 20, 40, 60}

func (i DroidOrderSybType) String() string {
	if i >= DroidOrderSybType(len(_DroidOrderSybType_index)-1) {
		return "DroidOrderSybType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DroidOrderSybType_name[_DroidOrderSybType_index[i]:_DroidOrderSybType_index[i+1]]
}
